name: Build and unit test then push to Dockerhub
run-name: ${{ github.actor }} is processing Frontend
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-images:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

          # for simple tests (npm test, etc.) just run a local image in docker
      - name: Docker Build and Push Frontend to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          target: production
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/socialpedia_frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max